### ISSUE TITLE
gulp 4 support.

### ISSUE THREAD

**Issue by iwan933** [udos86/ng-dynamic-forms#795]
## I'm submitting a
<pre><code>
[ ] Bug / Regression
[ x ] Feature Request / Proposal
[ ] Question
</code></pre>

## I'm using
<pre><code>
NG Dynamic Forms Version: `6.0.6`

[ ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[ ] Material  
[ ] NG Bootstrap
[ ] Prime NG
</code></pre>

## Description
Trying to set up the example it occurs that the gulp release of version 4 breaks the build. Error message below:

> npm run build:packages

> ng-dynamic-forms@6.0.6 build:packages D:\git\repositories\ng-dynamic-forms
> gulp build

[11:26:26] Using gulpfile ..\ng-dynamic-forms\gulpfile.js
[11:26:26] Starting 'build'...
[11:26:26] 'build' errored after 3.35 ms
[11:26:26] TypeError: gulp.hasTask is not a function
    at ..\ng-dynamic-forms\node_modules\run-sequence\index.js:23:22
    at Array.forEach (<anonymous>)
    at verifyTaskSets (..\ng-dynamic-forms\node_modules\run-sequence\index.js:17:11)
    at runSequence (..\ng-dynamic-forms\node_modules\run-sequence\index.js:130:2)
    at gulp.task.done (..\ng-dynamic-forms\gulpfile.js:157:5)
    at taskWrapper (..\ng-dynamic-forms\node_modules\undertaker\lib\set-task.js:13:15)
    at bound (domain.js:301:14)
    at runBound (domain.js:314:12)
    at asyncRunner (..\ng-dynamic-forms\node_modules\async-done\index.js:55:18)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ng-dynamic-forms@6.0.6 build:packages: `gulp build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ng-dynamic-forms@6.0.6 build:packages script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!    ..\npm-cache\_logs\2018-06-19T09_26_26_668Z-debug.log

**Comment by udos86** [comment]
@iwan933 

Upgrading currently would not bring any advantage to the project.   

I'll consider reopening this as soon as there is a stable version of Gulp 4.
